### ISSUE TITLE
Is posible to use for single page applications ?

### ISSUE THREAD

**Issue by Relaxe111** [static-web-server/static-web-server#23]
How can I allow clinent side routing with static-web server? Such that /user will not give me 404 but will let client side to do routing? 
Thnks.

**Comment by joseluisq** [comment]
This project is a web server to serve static files like whatever HTML apps such as SPAs, PWA, etc, but it doesn't take care about routes. It just maps files and directories to the server file system.

For SPAs, if your routes are defined on the client side using a `#/user` (`location.hash`) it doesn't affect your routes if you refresh your page because everything stays on browser (JS). So you can use it with this server.
However if you have defined your routes using the `history.pushState` or similar then if you try to reach `/user` (as you said) you will see only 404s because `/user` will be sent to the server by the browser, then the server will try to lookup for some directory that probably doesn't exist on it (remember: static files server).

So you want to enable `location.hash` on your Javascript SPA application in order to work with this server.
But if you insist on custom routes you can use a proxy on top of this server to reply your routes accordingly (bit more complicated). If you don't so then just use another server on Rust, other language or framework that can give you more freedom with routes.

**Comment by joseluisq** [comment]
BTW Recently we merged https://github.com/joseluisq/static-web-server/pull/91 that it could maybe help with SPAs. See [the docs](https://sws.joseluisq.net/features/error-pages/#fallback-page-for-use-with-client-routers).
