### ISSUE TITLE
Not a friendly SWS

### ISSUE THREAD

**Issue by ropucyka** [static-web-server/static-web-server#34]
No:
main page
auto indexing
uploads
user auth
permissions for files/folders access
...

Why listening ipv6 by default?
So feature charged and fast, but not for typical home use like this: https://github.com/mjpclab/go-http-file-server
Only for high skill users, programmers. Sad with it.

**Comment by joseluisq** [comment]
There are many topics in your issue I would like to see more specific issue descriptions to be able to tackle them more precisely.

--

> main page

What do you really mean?

> auto indexing

You already has directory listing introduced in the current [v1.14.0](https://github.com/joseluisq/static-web-server/releases/tag/v1.14.0).

> uploads

Unfortunately I have no plans to add uploads. Since it's not the goal of this server.

> user auth

Sounds fine, just file a feature issue if you want it and explain why the feature.

> permissions for files/folders access 

I don't get it, this is in your website side (at your option). Or do you mean a GUI to do it?

> Why listening ipv6 by default?

It's just a default value, you always can change it for something else. See `--host` option on README.

> So feature charged and fast, but not for typical home use like this: https://github.com/mjpclab/go-http-file-server
> Only for high skill users, programmers. Sad with it.

The server goal is to be a high performance server for production environments. But it doesn't mean that you can not use it on personal projects or local environments. However if there are no features that you would like to have and if you feel that a feature can be useful to add just file a feature issue and explain why that feature should be included, I'm open to discuss it.

Regarding the home usage, if the server is not user-friendly or it's too advanced to setup (BTW everything is explained in README file), I'm open to improve the documentation to make it more clear if not so. However don't hesitate to send a PR.

**Comment by ropucyka** [comment]
Just close this ticket.
