### ISSUE TITLE
Equivalent of `try_files` in nginx for Angular apps

### ISSUE THREAD

**Issue by richbayliss** [static-web-server/static-web-server#45]
# Problem
I was looking to use this as the HTTP server component in an Angular SPA but can't due to the routing mechanism in Angular.

# Question
Would you be welcome to the addition of a feature to `try_files` so that Angular SPA's might be served?

# Suggestion
Add support via a CLI argument, and code implementation like so:

```
--try-files "$uri $uri/ index.html"
```

...where `$uri` represents the requested path and is regex-replaced when finding the file to serve.

**Comment by richbayliss** [comment]
I am not a massive Rust guy (yet) but here's a PR to add such a feature: https://github.com/joseluisq/static-web-server/pull/46

**Comment by joseluisq** [comment]
I think that feature is not a bad idea at all if one wants to fallback on purpose to a specific html page.

**Comment by joseluisq** [comment]
Hi,
I was thinking around the idea of this feature and I have concluded that it will be not accurate solution for this server.
Here my explanation why.

Nginx `try_files` directive in general is more complex that just trying a list of uris one by one until the fallback page. Which implies overhead during look up depending on the list. (I have already mentioned something about it in your PR #46)

Nginx `try_files` has different context of usage and makes sense there (For example with: location directive, proxy directive, etc). But in `static-web-server` project either `$uri` (whatever uri) and `$uri/` (whatever dir) are implicit, meaning that the server is managing those by default depending of the user request. So for example a `"try_files $uri $uri/ =404"` equivalent is redundant.

However the only thing which I see as a possibility is the fallback uri (the last parameter of `try_files`). Since this issue wants for example to redirect all request uris to another specific html page uri.
But there is a caveat with it. For example, one could introduce another flag option like `--fallback-location=/index.html` or whatever to indicate the purpose. But this could be a *temporary workaround* but I don't see it as a long-term solution since users could want to be able to fallback more than one page with not necessarily the same uri.

Nonetheless, what I could propose is to add support for _**customizable routes**_.
With this option users could add whatever routes they want to map their pages uris more precisely. But this implies necessarily to implement support for a custom config file. Something that I see factible in near future by the way.

If in the eventually case we would add routes support, then a `--fallback-location` flag option doesn't make sense or even worse if we add the fallback flag first then will make annoying (for users) to deprecate it in favor of _customizable routes_ for example.

So It's not because it's a bad idea something like `try_files` but _customizable routes_ might be even better in different aspects.

I'm going to close the issue however feel free to let your comments or concerns.

**Comment by joseluisq** [comment]
It relates to the Fallback Page feature implemented by #91
More details at https://sws.joseluisq.net/features/error-pages/#fallback-page-for-use-with-client-routers
